task_dict:
  import:
    - ./components/tasks/db_bench.yaml
    - ./components/tasks/os_interaction.yaml
    - ./components/tasks/knowledge_graph.yaml
language_model_dict:
  import:
    - ./components/language_models/openai_language_model.yaml
    - ./components/language_models/huggingface_language_model.yaml
agent_dict:
  import:
    - ./components/agents/fixed_response_agent.yaml
    - ./components/agents/language_model_agent.yaml
    - ./components/agents/oracle_agent.yaml
callback_dict:
  import:
    - ./components/callbacks/previous_sample_utilization_callback.yaml
    - ./components/callbacks/current_session_saving_callback.yaml
    - ./components/callbacks/group_self_consistency_callback.yaml
    - ./components/callbacks/consecutive_abnormal_agent_inference_process_handling_callback.yaml
    - ./components/callbacks/test_time_training_callback.yaml #新建的sft call_back
    - ./components/callbacks/workflow_memory.yaml #AWM Online workflow memory
    - ./components/callbacks/trajectory_memory_callback.yaml #总结+召回topk
    - ./components/callbacks/test_time_training_assistant_only_callback.yaml #只训练assistant输出的sft call_back

import:
  - ./components/logger.yaml
  - ./components/environment.yaml