os_interaction:
  module: "src.tasks.instance.os_interaction.OSInteraction"
  parameters:
    task_name:
      module: "src.typings.TaskName"
      parameters:
        value: "os_interaction"
    chat_history_item_factory:
      module: "src.factories.chat_history_item.ChatHistoryItemFactory"
      parameters:
        chat_history_item_dict_path: "./chat_history_items/standard/os_interaction.json"
    data_file_path: "./data/os_bench.json"
    max_round: 5
    command_execution_timeout: 20